"""empty message

Revision ID: 61144c685e98
Revises: 4bf45c01dc3c
Create Date: 2020-07-26 04:50:35.654648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61144c685e98'
down_revision = '4bf45c01dc3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'study')
    op.drop_column('teachers', 'work')
    op.drop_column('teachers', 'program')
    op.drop_column('teachers', 'relocate')
    op.drop_column('teachers', 'travel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('travel', sa.BOOLEAN(), nullable=False))
    op.add_column('teachers', sa.Column('relocate', sa.BOOLEAN(), nullable=False))
    op.add_column('teachers', sa.Column('program', sa.BOOLEAN(), nullable=False))
    op.add_column('teachers', sa.Column('work', sa.BOOLEAN(), nullable=False))
    op.add_column('teachers', sa.Column('study', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
